export const REQUEST_PRODUCT_DATA = "REQUSET_PRODUCT_DATA";
export const SUCCESS_PRODUCT_DATA = "SUCCESS_PRODUCT_DATA";
export const FAILURE_PRODUCT_DATA = "FAILURE_PRODUCT_DATA";
export const REMOVER_DATA = "REMOVE_DATA"